<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ComiCal.Tests.Unit</RootNamespace>
    <AssemblyName>ComiCal.Tests.Unit</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\backend\domain\ComiCal.Domain.csproj" />
    <ProjectReference Include="..\..\..\backend\application\ComiCal.Application.csproj" />
    <ProjectReference Include="..\..\..\backend\infrastructure\ComiCal.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\backend\shared\ComiCal.Shared.csproj" />
    <ProjectReference Include="..\..\..\backend\api\ComiCal.Api.csproj" />
    <ProjectReference Include="..\..\..\backend\batch\ComiCal.Batch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
