namespace ComiCal.Batch.Models;

/// <summary>Top-level orchestrator input. <see cref="RunId"/> is generated by the caller (trigger), not the orchestrator.</summary>
public sealed record BatchRunInput(string Keyword, int MaxPages, Guid RunId);

/// <summary>Manual trigger HTTP body.</summary>
public sealed record ManualTriggerRequest(string? Keyword, bool DryRun);

/// <summary>Activity input for fetching a single Rakuten search-result page.</summary>
public sealed record FetchRakutenPageInput(string Keyword, int Page);

/// <summary>
/// JSON-friendly volume payload passed between orchestrator and activities.
/// Mirrors <c>ComiCal.Infrastructure.Rakuten.RakutenIngestPayload</c> but with
/// primitive types so Durable Task serialization is deterministic across replays.
/// </summary>
public sealed record BatchVolumePayload(
    string Isbn,
    string Title,
    string SeriesName,
    string SeriesNameKana,
    int? VolumeNumber,
    DateOnly? ReleaseDate,
    bool ReleaseDateIsMonthOnly,
    string AuthorName,
    string AuthorKana,
    string PublisherName,
    string? ItemUrl,
    string? CoverImageUrl);

/// <summary>Result of one <c>UpsertSeriesAndVolume</c> activity invocation.</summary>
public sealed record UpsertResult(
    Guid VolumeId,
    bool IsNew,
    string Isbn,
    string? CoverUrl,
    byte[]? CurrentCoverHash);

/// <summary>Activity input for cover thumbnail download.</summary>
public sealed record CoverDownloadInput(
    string Isbn,
    Guid VolumeId,
    string CoverUrl,
    byte[]? CurrentCoverHash);

/// <summary>Aggregated counts written to <c>BatchRuns</c> on success.</summary>
public sealed record BatchRunSummary(int FetchedItems, int UpsertedVolumes, int FailedItems);

public sealed record FinishBatchRunInput(Guid RunId, BatchRunSummary Summary);

public sealed record FailBatchRunInput(Guid RunId, string Error, IReadOnlyList<FailedItemRecord> Failed);

public sealed record FailedItemRecord(string ItemKey, string Reason, string? PayloadJson);
