<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ComiCal.Infrastructure.Blob</AssemblyName>
    <RootNamespace>ComiCal.Infrastructure.Blob</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../domain/ComiCal.Domain/ComiCal.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>
</Project>
