name: ApiFunctions CI/CD

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/api-functions-deploy.yml

env:
  AZURE_FUNCTIONAPP_NAME: 'comical-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'api'
  DOTNET_VERSION: '6'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@main

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.3.1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_API }}